# Base configs
baseurl: ""
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Shruti Sharma"
subtitle: "See the world through my eyes!"
author: "Shruti Sharma"
header:
 title: "Photography"
 subtitle: "by Shruti Sharma"
footer:
 name: "Artist Statement"
 bio: "insert artist statement here"
# web_design: "AJ"
social_urls:
  # facebook: "https://www.facebook.com/ramswaroop"
  # twitter: "https://www.twitter.com/ram__patra"
  # instagram: "https://www.instagram.com/ram_patra"
  # dribbble: "https://dribbble.com/rampatra"
  # linkedin: "https://in.linkedin.com/in/ram-patra"
  # github: "https://www.github.com/rampatra"
