# Base configs
baseurl: "photography-portfolio"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Shruti Sharma"
subtitle: "See the world through my eyes!"
author: "Shruti Sharma"
header:
 title: "Photography"
 subtitle: "by Shruti Sharma"
footer:
 name: "Artist Statement"
 bio: "\"You're only here for a short visit. Don't hurry. Don't worry. And be sure to smell the flowers along the way.\" </br>- Walter Hagen </br></br>I find beauty in the seemingly mundane everyday objects and events. Especially during the quarantine, as we have all been confined to our homes and neighborhoods with not many options to travel, I have learned to look at everything around me with a fresh lens and find fascinating new details in the same things I’ve seen every day for years. </br></br> I like to get up close to the subjects I’m photographing and use tight crops to direct the viewer’s attention towards what I saw in the moment that compelled me to take a picture.  I capture images with distraction-free backgrounds and achieve those looks without a studio backdrop setting. My visual aesthetic and framing of a shot is inspired by symmetry seen in nature which shows up more intensely in man-made objects."
# web_design: "AJ"
social_urls:
  # facebook: "https://www.facebook.com/ramswaroop"
  # twitter: "https://www.twitter.com/ram__patra"
  # instagram: "https://www.instagram.com/ram_patra"
  # dribbble: "https://dribbble.com/rampatra"
  # linkedin: "https://in.linkedin.com/in/ram-patra"
  # github: "https://www.github.com/rampatra"
